### ISSUE TITLE
App isn't working out of the box

### ISSUE THREAD

**Issue by psi-gh** [rancavil/tornado-openshift-quickstart#2]
When i completed all steps in tutorial, app doesn't work. I get Internal Server Error when open url of my new app.

**Comment by OrkoHunter** [comment]
**Ping**. This happened with me too. Simply following it did not render the `index.html`.
I get this on opening the webpage.

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Apache/2.2.15 (Red Hat) Server at linux2-pingme.rhcloud.com Port 80
```

**Comment by rancavil** [comment]
Thanks for the feedback...the problem occurs because the tornado package could not be downloaded and therefore not installed. We solved the problem by using the requirements.txt file.

Please, let me know if this work or not

**Comment by OrkoHunter** [comment]
This worked! We may close the issue now.
