### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by OrkoHunter** [rancavil/tornado-openshift-quickstart#3]
@rancavil I set up the application and it's working fine when I open the url in my browser. It displays

```
Congrats you have Tornado Web Server running on OpenShift!!!
Enjoy!!!
```

But I don't think that CORS is enabled there. Because when I try to read the page using `XMLHttpRequest` in javascript, it says

```
XMLHttpRequest cannot load http://XXX.rhcloud.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://XYZ.com' is therefore not allowed access.
```

Can you please help me regarding this? We need to reconfigure the server and allow Cross Origin Access.

**Comment by rancavil** [comment]
The problem is not the Tornado deployment in OpenShift or ....

To resolve this problem you must set CORS in the response headers.

You can see a example in: http://innovaser.cl/innovaser.php/2016/01/11/tornado-web-server-cors
